# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: tofu-frontend CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: '**/node_modules'
        restore-keys: |
           ${{ runner.os }}-node-
        
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install
      
    - name: build
      run: yarn build 

    # - name: Docker Login
    #   uses: docker/login-action@v2.2.0
    #   with:
    #     registry: 
    #     username: ${{secrets.DOCKERHUB_USER}}
    #     password: ${{secrets.DOCKERHUB_ACCESS_TOKEN}}

    # - name: Build and push Docker images
    #   uses: docker/build-push-action@v4.1.1
    #   with:
    #     context: .
    #     file: ./Dockerfile
    #     push: true
    #     tags: tofu-frontend
    #     labels: latest
